name: citi_guide_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  supabase_flutter: ^2.8.4
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.11.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  path: ^1.9.0
  cached_network_image: ^3.4.1
  lucide_icons: ^0.257.0 
  async: 2.12.0  # Make sure this is up-to-date

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: ^14.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/loading.json
    - .env
